/*
 * Javautveckling 2018
 */
package pac;

import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.enterprise.context.Dependent;

/**
 *
 * @author 01phi
 */
@Named(value = "betalning")
@Dependent
public class Betalning implements Serializable {

        public String kort;
	public String faktura;
	public String swish;
			
	public String getKort() {
		return kort;
	}

	public void setKort(String kort) {
		this.kort = kort;
	}

	public String getFaktura() {
		return faktura;
	}

	public void setFakura(String faktura) {
		this.faktura = faktura;
	}

	public String getSwish() {
		return swish;
	}

	public void setSwish(String swish) {
		this.swish = swish;
	}

	//Generated by Map
	private static Map<String,Object> betalning;
	static{
		betalning = new LinkedHashMap<String,Object>();
		betalning.put("betalning - Kort", "Kort"); //label, value
		betalning.put("betalning - Faktura", "Faktura");
		betalning.put("betalning - swish", "Swish");
	}
	
	public Map<String,Object> getBetalning() {
		return betalning;
	}
        
	
    public Betalning() {
    }
    
}
